### ISSUE TITLE
Feature Request: MSU symlinking option

### ISSUE THREAD

**Issue by Formedras** [RadzPrower/Zelda-3-Launcher#11]
Please provide an option to use a symbolic link to route to the directory where the MSU files are located, instead of copying them into the `%Zelda3Launcher%\zelda3\msu` folder. <br/> By using symlinks, you save on the user's disk space (a single directory link is a cluster or two, while a full MSU set can be over half a gig). And unless an app is specifically looking for symlinks (or similar), they're transparent to said app. It just works.

But also please keep it **an option**. On Windows, symlinks only work on NTFS filesystems and cannot be used on FAT32 or exFAT, both still commonly used on removable media like flash drives and SD cards. It should additionally either be off by default, and/or allow falling back to normal file copying.

**Comment by RadzPrower** [comment]
Not a bad idea. I will have to run some tests to see if the `zelda3` executable will work with them before I actually consider putting any work into it.

If I do move forward with any development, I'll need to rearrange the GUI to make space for the option. Depending on what would be needed for the code, it might be easier to just try symlink and catch if it fails and fall back to copying. Won't really know until I do more research and testing.

**Comment by Formedras** [comment]
I tested it myself before making the request. (In fact, while I was typing it out.) It works fine. I put the standard orchestral soundtrack in `C:\Games\Z3Launcher\Custom\Music\Orchestral`, used [Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) to link `C:\Games\Z3Launcher\zelda3\msu` to it, and it works perfectly.

Oh, yeah, the function you'll probably want to use is [File.CreateSymbolicLink(string,string)](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.createsymboliclink?view=net-7.0).

**Comment by Formedras** [comment]
Pull request #13 implements this request.
