### ISSUE TITLE
Is it possible to use custom rom with translation?

### ISSUE THREAD

**Issue by legovo** [RadzPrower/Zelda-3-Launcher#14]
I have a patched Zelda rom with translation, and it's based on the US version, and the overall offsets are the same, but there may be some code patches that make this translation not work properly. I don't know if it can really work, but I can't even try to find out. I think there should be a way to try building the game with a custom ROM, not just a hardcoded hash check.

**Comment by RadzPrower** [comment]
That is an issue that needs to be taken up with the game developer. I have just created a wrapper to make the build and settings management process easier. Direct issues specifically regarding the game to [snesrev](https://github.com/snesrev/zelda3).
