### ISSUE TITLE
Unable to find Spanish patch

### ISSUE THREAD

**Issue by Sir-BLaDE** [RadzPrower/Zelda-3-Launcher#20]
I am unable to find what Spanish patch you are using, since the game never existed in Spanish without patch.
The search for the hash sha-1 461FCBD700D1332009C0E85A7A136E2A8E4B111E does not give any results.

Thank you for your amazing work by the way.

**Comment by RadzPrower** [comment]
This is the patch linked in the code from snesrev's repository: [https://www.romhacking.net/translations/2195/](https://www.romhacking.net/translations/2195/)

Be aware though that I tried some patches in my testing and could not get matching results to what their tools require either. If you still cannot get a proper hash after patching, you will need to bring it up to snesrev directly.
