### ISSUE TITLE
Feature Request: Hotkeys to exit and reset the game.

### ISSUE THREAD

**Issue by TomTurbine** [RadzPrower/Zelda-3-Launcher#21]
Thinking of this when using it with a front end on a controller, just to be able to bind a hotkey to exit the game for you.

Also a good feature for any other launchers. Thank you for your work, much appreciated.

**Comment by RadzPrower** [comment]
Any functionality of the game itself will need to be addressed to snesrev on their project rather than myself and the launcher. The launcher simply builds their project.

**Comment by TomTurbine** [comment]
Understood, I thought the ability to send a reset signal or close was handled by the launcher, my bad.
