### ISSUE TITLE
Application does not create zelda3_assets.dat

### ISSUE THREAD

**Issue by pseudo3d** [RadzPrower/Zelda-3-Launcher#22]
While I was able to launch the application (which needs .NET framework), the process did not create a zelda3_assets.dat based on the correct ROM. I am not sure why it did not compile it from zelda3.sfc.

I had issues creating the same thing with MSYS64 (dependencies required, it was a big mess), but the launcher from what I've read is supposed to do all this automatically.

**Comment by RadzPrower** [comment]
Did it present you with any error messages? Can you provide the log file from where you attempted to compile?

**Comment by pseudo3d** [comment]
I've fiddled around with some stuff so the error log will have records of that but the most recent from this morning should show the latest.
[zelda3.log](https://github.com/RadzPrower/Zelda-3-Launcher/files/11857431/zelda3.log)

**Comment by RadzPrower** [comment]
Nothing stands out immediately, so I'll need to double-check the original project and see if the build process has been changed in a way that would make the launcher out-of-date.

**Comment by RadzPrower** [comment]
I just downloaded a clean copy of the launcher from GitHub and ran the process which worked as expected. In comparing our logs though, I am seeing some differences, notably in regards to how the version of python the launcher downloads. All of the python calls are entirely empty in your log where mine is actually returning the messages from those commands.

This leads me to believe that you may be having a problem download that version of python as its possibly being blocked by some firewall, device security, or it may have even just been down when the download was attempted. Please check the `/tables` folder for a `python.exe` to see if it is present.

**Comment by pseudo3d** [comment]
There is a python.exe with the modification date of 9/5/2022.

I remember when trying to build Super Mario 64 and its builder it had issues with Avast.

**Comment by pseudo3d** [comment]
I decided to whitelist it from Avast, rebuild it again, and got python.exe - System Error.

"The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

**Comment by RadzPrower** [comment]
What version of Windows are you running? Some quick searching indicates that your error may be due to your Windows version being no longer supported by the version of python I download and use.

**Comment by pseudo3d** [comment]
Windows 7, which msys64 no longer officially supports...I had to go back to an old version when I was using the SM64 builder. I didn't see system requirements, and .NET framework still worked, so I assumed it was valid. I'm surprised I'd be the first to find that out that way.

**Comment by RadzPrower** [comment]
Consider attempting with the new v1.3.1.0 release as the python version was updated. It may actually have been related to that all along.
