### ISSUE TITLE
Launcher failing while installing dependencies

### ISSUE THREAD

**Issue by Whyexes** [RadzPrower/Zelda-3-Launcher#23]
Seems to be an issue with pillow specifically but Im not too sure how to read it. 

[zelda3.log](https://github.com/RadzPrower/Zelda-3-Launcher/files/11951418/zelda3.log)

**Comment by tcmbackwards** [comment]
Same error here, the launcher is building the Pillow wheel from source but zlib-devel is required and there's no easy way in Windows to automatically install zlib-devel. Building pillow with --global-option="build_ext" --global-option="--disable-zlib" --global-option="--disable-jpeg" no longer works either. Pillow has prebuilt wheels to download but they're all 64 bit and the launcher uses a 32 bit build of python.

**Comment by DustbinK** [comment]
I can also confirm the error and the logs state it's failing at pillow as others have noted.

**Comment by SteamDeckHelpNeeded** [comment]
I just want to add that I'm having the same issue. The error says it can't install dependencies.

**Comment by Caseylee6** [comment]
same issue.

**Comment by TimmyP777** [comment]
Wow this is open source at its usual

**Comment by TimmyP777** [comment]
Doesnt even work on an intel machine surface pro

**Comment by RadzPrower** [comment]
Python version was updated with release v1.3.1.0 and should now use the version currently recommended in snesrev's project.
