### ISSUE TITLE
English (Redux)

### ISSUE THREAD

**Issue by EliParker28** [RadzPrower/Zelda-3-Launcher#27]
No matter what version of the redux mod, I am getting the invalid ROM hash. Is there a way for this to bypass this, so we can play the redux translation with your launcher.

**Comment by RadzPrower** [comment]
Assuming the hash doesn't match, that means data is going to be different from what is expected and may well cause the whole thing to crash. That's why the original project checks the hash as well.

I will look and see if they've updated to a different hash though and update it here if they have.

**Comment by RadzPrower** [comment]
I have checked and my hashes match the ones that snesrev's project expects.

Here are the hashes as pulled from the snesrev repository just now:
`B2A07A59E64C498BC1B2F28728F9BF4014C8D582`
`9325C22EB0A2A1F0017157C8B620BC3A605CEDE1`

Even if I removed my graphical interface hash check, the project would still fail to build as it simply runs snesrev's code and therefore it would still fail but without elegantly telling you ahead of time.
