### ISSUE TITLE
Keymapper Utility controller image size mismatch.

### ISSUE THREAD

**Issue by impeeza** [RadzPrower/Zelda-3-Launcher#36]
Hello there on my PC the Keymapper utility the controller picture is the wrong size.

![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/993926e7-152f-4c83-a08d-fe9e6ef4da70)

The green arrow shows the border of controller image, and the yellow one shows the container limit.

My display settings are:

![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/533e76ad-c287-4ab7-871f-4653db116ecc)

Changing the Display DPI also change the display of Keymapper controller image:
![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/ed3ebc3b-b0d4-4cca-acc4-9dc869fb8525)

may be code should be added to resize the controller image to the appropriate size of the container and take in account the DPI of the display.

putting my display to 100% scale the image is shown correctly:

![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/879f0af3-98c4-45af-aef5-7f46520f916b)

**Comment by RadzPrower** [comment]
Scaling is not exactly a critical concern considering it is a non-standard scenario, but next time I load up the code, I'll see if there's a simple solution.

**Comment by impeeza** [comment]
Thank you, I did try to look into the code but I haven programmed so long time what I didn't understand anything  :D

back on my days the code was on the load method of the form, but today I got lost. 🤣

**Comment by impeeza** [comment]
Today tried to dust off my programming knowledge and even if Visual Studio is making me crazy, I managed to find the only little change needed:

The «PictureController» object is the picture container and have a property called «SizeMode» which is on «AutoMode»:
![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/153e01df-e111-4c79-9adf-7e1cb8179a17)
On this mode the image keeps his original size.

but if you change it to «StretchImage»:
![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/91214cc0-b7b1-47fd-9e1c-16963c436934)
the image get automatically the size of the container, and as Windows Forms is taking care of autoscale all forms components the image is drawn on all DPIs correctly:
![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/e5c8bbc5-e246-4868-887c-5c92362b2400)
![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/7fc92aa0-1107-4612-9676-7655e1a06b29)

![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/df155e1a-1f97-4a93-92b9-8d4d57ff4fed)

The only change needed on the source code is:

line 108 on «keymapper.Designer.cs» file:

![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/d55bfd9a-fd54-4fb5-98aa-4e9715767f0f)

do you mind if I create a PR?

**Comment by RadzPrower** [comment]
I'm curious what version of Windows you are running?

I've changed the scaling on my PC and it's properly scaling at 125% and 150%. I'd rather not simply change to `StretchImage` since it appears from your screenshots that it's not maintaining aspect ratio.

**Comment by impeeza** [comment]
> I'm curious what version of Windows you are running?
> 
> I've changed the scaling on my PC and it's properly scaling at 125% and 150%. I'd rather not simply change to `StretchImage` since it appears from your screenshots that it's not maintaining aspect ratio.

Hello there. I am on windows 11 and both of my pcs have the same behavior

**Comment by RadzPrower** [comment]
I'm also on Windows 11 and I can push it to absurd levels of scaling and it's just fine:
![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/37708128/e6a9a8a2-24c4-4fd0-b5a2-62d8cabefa0a)

So, I am not sure what is causing the different behavior between our machines.

**Comment by impeeza** [comment]
I don't know too, may be the monitor? will test this night with others monitors, resolutions, etc.

I am using only 1080 res far now.

**Comment by impeeza** [comment]
Just connect a 4K monitor to my PC and my Laptop and found what on any resolution bigger than 1920X1080 do not matters which scale you select the picture is drawn correctly.

But for all resolutions equal and lower than 1920X1080 if you select a scale bigger than 100% the controller image get at wrong size. And with a scale of 100% the image is perfect.

Only happens with 1920X1080 or smaller resolutions.

It's Wired.

Tested on my Laptop and Desktop Windows 11 22621.2215 build

**Comment by RadzPrower** [comment]
I'll see if lowering my resolution will let me at least replicate and see about finding a way to fix it while maintaining aspect ratio.

**Comment by impeeza** [comment]
thank you

**Comment by RadzPrower** [comment]
![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/37708128/5a2fdb8a-bcf7-48bd-a5f8-d73a28ec405f)
Even at a lower resolution (as low as 1280x720) and with scaling up to 175% I have not seen the odd resizing issue.

**Comment by impeeza** [comment]
he he he,  should be my PCs are haunted! let see if somebody is experiencing the same but for now put a pin on the issue.

Thanks a lot for your help and work.

**Comment by RadzPrower** [comment]
I'd be curious to see if it's a particular graphics card, brand, or even driver version that's the culprit.

**Comment by impeeza** [comment]
Maybe,  I have:

PC:
- Display Adapter: Intel HD Graphics 530 31.0.101.2115
- Monitor: Acer VG270S
- Windows 11 22H2 Build 22621.2215

Laptop:
- Diplay Adapter: Intel UHD Graphics 31.0.101.2114
- Monitor: Wide viewing angle & High density FlexView Display 1920X1080
- Windows 11 22H2 build 22621.2134
regards

**Comment by RadzPrower** [comment]
PC drivers seem up-to-date while the Laptop is one version behind, but the problem is present in both. The laptop Windows 11 version is the same as mine and the PC one is actually higher.

As far as I can tell, the most likely culprit at this point would be the Intel hardware itself. I don't have anything with an Intel chipset to verify though.
