### ISSUE TITLE
Closing windows do not give warning

### ISSUE THREAD

**Issue by impeeza** [RadzPrower/Zelda-3-Launcher#37]
When you close the Keymapper Utility window using the cancel button you get this warning:

![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/4e5e09ee-2ead-4b53-b7ce-1bc644c44fff)

But if you close the dialog using the close button at top, the dialog is closed but you don't get the warning.
![image](https://github.com/RadzPrower/Zelda-3-Launcher/assets/41979604/cb80d47a-d1a2-4bfc-a200-d6778febc2a7)

The same happen to settings dialog.

**Comment by RadzPrower** [comment]
Functionality has been made uniform between the Close and Cancel buttons

Will be included in release v1.3.6.0.
