### ISSUE TITLE
Incorrect hash for Redux

### ISSUE THREAD

**Issue by ColossusSteppes** [RadzPrower/Zelda-3-Launcher#38]
Using the Redux Retranslation patch on my ALTTP rom `6D4F10A8B10E10DBE624CB23CF03B88BB8252973`, I'm getting a patched rom with the hash `E3FE7A17C90BD0F39736A51EFF444B216AF5ADE0`.

But when changing the language to Redux, it asks for a patched rom with the hash `9325C22EB0A2A1F0017157C8B620BC3A605CEDE1`.

Can you confirm that it's Redux v10.2.2 found [here](https://github.com/ShadowOne333/A-Link-to-the-Past-Redux/releases/tag/v10.2.2) and [here](https://www.romhacking.net/hacks/2594/), patched with LunarIPS, found [here](https://www.romhacking.net/utilities/240/)?

**Comment by RadzPrower** [comment]
I cannot confirm any version numbers or hashes other than to say that they matched the hashes from the main project as of the last time I checked them. It is highly unlikely they've been updated in the last week or so as the project has been largely been abandoned for months.

Many of the hashes did not match what I found when I was building this functionality initially either (which means many translations I was not even able to test) and it was brought up to the developer at that time but nothing came of it.

**Comment by ColossusSteppes** [comment]
Hey, I've been looking into this again and it seems that the launcher requries the [v10.1 version of Redux](https://github.com/ShadowOne333/A-Link-to-the-Past-Redux/tree/main/old-redux-versions), rather than the current version.

**Comment by dwaaad** [comment]
> Hey, I've been looking into this again and it seems that the launcher requries the [v10.1 version of Redux](https://github.com/ShadowOne333/A-Link-to-the-Past-Redux/tree/main/old-redux-versions), rather than the current version.

Did this work for you? Patching this to my own ROM gave me this error:

![Image](https://github.com/user-attachments/assets/f28565da-61c6-4b1a-bbe6-d969f01e3a2a)
