### ISSUE TITLE
Can't use a French ROM (or any other language than US)

### ISSUE THREAD

**Issue by fhivet** [RadzPrower/Zelda-3-Launcher#9]
Hi

Wanted to use this tool cause I don't have any developer skills, but there is no way to use another ROM than the US one.

Can you add support for other language?

**Comment by RadzPrower** [comment]
That is outside the scope of this tool. This is simply a simpler interface to the main project by snesrev. Any changes regarding the game itself and ROM compatibility will need to be directed there.
